# -*- coding: utf-8 -*-
"""SENAI-Python-Lista-Atividades-3-WHILE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aABs-2dPyyHVYjNIdYv1Sczk_ykheBjr

## 1. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

while True:
  nota = float(input("Digite a nota apenas entre 0 e 10: "))
  if nota >= 0 and nota <= 10:
   print("Nota cadastrada")
   break
  else:
   print("Invalido por favor coloque a nota valida")

"""## 2. Faça um programa que calcule o mostre a média aritmética de N notas."""

notas = 0
i = 0
continuar = "S"

while continuar == "S":
  nota = float(input("Digite uma nota: "))
  notas += nota
  i += 1
  continuar = input("Deseja continuar? Sim(S) Nao(N): ").upper()

print(f"A media das notas e {notas / i:.2f}")

"""## 3. Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações"""

while True:
  usuario = str(input("Digite o usuario: "))
  senha = str(input("Digite a senha: "))
  if usuario != senha:
    print("Login cadastrado com sucesso!")
    break
  else:
    print("Usuario e senha nao podem ser o mesmo, insira um usuario e senha diferentes!")

"""## 4. Um funcionário de uma empresa recebe aumento salarial anualmente. Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário.

"""

salarioInicial = float(input("Digite o salário inicial do funcionário: "))
anoAtual = int(input("Digite o ano atual: "))

percentual_aumento = 0.015
ano = 1995

while ano < anoAtual:
    aumento = salarioInicial * percentual_aumento
    salarioInicial += aumento
    percentual_aumento *= 2
    ano += 1
    print(f"O salário atual do funcionário do ano {ano} é de R${salarioInicial:.2f}.")

"""## 5. Faça um programa que leia e valide as seguintes informações:
- Nome: maior que 3 caracteres;
- Idade: entre 0 e 150;
- Salário: maior que zero;
- Sexo: 'f' ou 'm';
- Estado Civil: 's', 'c', 'v', 'd';
"""

nome = str(input("Insira o nome: "))
while len(nome) <= 3:
  nome = str(input("Insira o nome novamente com mais de 3 caracteres: "))

idade = int(input("Insira a idade: "))
while idade < 0 or idade >150:
  idade = int(input("Insira a idade valida entre 0 e 150: "))

salario = float(input("Insira o salario: "))
while salario <= 0:
  salario = float(input("Insira o salario maior que 0: "))

sexo = str(input("Insira o sexo, F ou M: "))
while sexo != "F" and sexo != "M":
 sexo = str(input("Insira o sexo novamente, F ou M: "))

estadoCivil = str(input("Insira o estado civil, S, C, V, D: "))
while estadoCivil != "S" and estadoCivil != "C" and estadoCivil != "V" and estadoCivil != "D":
  estadoCivil = str(input("Insira o estado civil novamente, S, C, V, D: "))

print("")
print(f"Cadastreo realizado com sucesso \n Nome: {nome} \n Idade: {idade} \n Salario: {salario} \n Sexo: {sexo} \n Estado Civil: {estadoCivil} \n")

"""## 6. Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento."""

populacaoA = 80000
populacaoB = 200000
ano = 0

while populacaoA < populacaoB:
  populacaoA += populacaoA * 0.03
  populacaoB += populacaoB * 0.015
  ano += 1

print(f"ano {ano}, Populacao A: {populacaoA} e Populacao B: {populacaoB}")

"""## 7. Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120"""

numero = int(input("Fatorial de: ") )

i = 1
i2 = 1

while i <= numero:
    i2 *= i
    i += 1

print(f"O fatorial do {numero} será {i2}")

"""## 8. Faça um programa que solicite ao usuário números indefinidamente até que ele digite 0. Em seguida, o programa deve imprimir a média dos números digitados.

"""

soma = 0
i = 0

while True:
    numero = float(input("Digite um número ou 0 para sair: "))

    if numero == 0:
        break
    soma += numero
    i += 1

if i != 0:
    media = soma / i
    print(f"A média dos números digitados é: {media}")
else:
    print("Nenhum número foi digitado.")

"""## 9. A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um programa capaz de gerar a série até o nésimo termo."""

ultimo = 1
penultimo = 1
i = 1
print(ultimo)
print(penultimo)
while i <= 20:
  termo = ultimo + penultimo
  penultimo = ultimo
  ultimo = termo
  i += 1
  print(termo)

"""## 10. O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e agora possui uma loja de conveniências. Faça um programa que implemente uma caixa registradora rudimentar.
- O programa deverá receber um número desconhecido de valores referentes
aos preços das mercadorias. Um valor zero deve ser informado pelo
operador para indicar o final da compra.
- O programa deve então mostrar o total da compra e perguntar o valor em
dinheiro que o cliente forneceu, para então calcular e mostrar o valor do
troco. Após esta operação, o programa deverá voltar ao ponto inicial, para
registrar a próxima compra.
- A saída deve ser conforme o exemplo abaixo:
- Lojas Tabajara
- Produto 1: RS 2.20
- Produto 2: RS 5.80
- Produto 3: RS 0
- Total: RS 9.00
- Dinheiro: RS 20.00
- Troco: RS 11.00
"""

total = 0
produto = 0
valor = 0

print("====Lojas Tabajara====")
print("")

while True:
  produto += 1
  total += valor
  valor = float(input(f"Produto {produto}: R$"))
  if valor == 0:
    produto = 0
    valor = 0
  print(f"Total da da compra foi R${total:.2f}")
  dinheiro = float(input("Dinheiro recebido: R$"))
  print(f"Troco: R${dinheiro - total}")
  total = 0

  print("====Lojas Tabajara====")
  print("")

"""## 11. O cardápio de uma lanchonete é o seguinte:
Especificação Código Preço
- Cachorro Quente 100 RS 1,20
- Bauru Simples 101 RS 1,30
- Bauru com ovo 102 RS 1,50
- Hambúrguer 103 RS 1,20
- Cheeseburguer 104 RS 1,30
- Refrigerante 105 RS 1,00

Faça um programa que leia o código dos itens pedidos e as quantidades desejadas.

Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.
"""

total = 0.00
produto = 100

print('''
█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
█░░╦─╦╔╗╦─╔╗╔╗╔╦╗╔╗░░█
█░░║║║╠─║─║─║║║║║╠─░░█
█░░╚╩╝╚╝╚╝╚╝╚╝╩─╩╚╝░░█
█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█

Seja bem vendo a lanchonte mais legal do mundo!!!

⡯⡯⡯⣯⢯⢿⢽⠝⡰⡭⣫⡓⠝⠈⠑⠉⠈⠑⠙⠝⣸⢿⡽⣯⢿⣽⣻⡽⡨⡊
⡯⡯⣟⣽⢽⢯⢋⢔⢽⠉⢁⢠⡰⣬⡪⠬⢄⡡⡠⠄⠈⢿⡽⡯⣟⣾⣳⡯⢏⠯
⡯⡿⡽⣞⡯⡏⡢⡡⠁⠰⠘⠘⢼⡰⢔⠖⣆⠬⠐⠁⢂⠈⢻⣽⣻⣞⡷⡏⡰⢈
⡯⣟⡽⠓⠋⠁⣠⠄⠠⠑⠐⠑⠄⢀⠈⠉⡀⠈⠐⠐⠐⠄⠄⣁⠑⠑⠻⣳⢵⣳
⣈⣀⢤⢤⢶⡻⠃⠄⡢⠓⠁⠐⢀⠑⠍⢉⠃⠁⠐⠄⠂⠆⠄⠙⠽⡦⣄⠈⠙⠺
⠓⡩⠩⠩⠃⠄⠄⠄⢅⢰⠉⢰⡀⡰⣴⡢⠄⠢⣗⠁⡆⠄⠄⠄⠄⠈⠝⠩⠢⠄
⠄⠄⠁⠌⠂⡲⡄⠄⡪⣂⢉⢈⡰⣺⣺⢽⣀⠁⡀⡀⠄⠂⠄⡯⡛⠌⠄⠡⠨⠈
⣠⢤⣀⣀⡀⠄⠄⠄⢈⠪⡲⣵⠉⠈⠈⠍⠈⠁⣗⢆⠊⠄⢀⣀⣀⢤⣲⡒⡠⠄
⡯⣯⢯⣟⡾⡽⡶⣄⠄⢂⠩⡺⡥⡦⣕⣤⡢⠈⢎⠐⠄⡰⣯⢷⣻⢽⣝⡇⣴⡕
⡯⣗⣿⣺⢽⡪⡯⣻⡄⠐⠨⡘⠌⠉⠈⠈⠨⢑⢀⠊⢠⢿⢽⣝⠮⠋⠐⠘⠑⠁
⠯⢗⣗⡯⣷⢝⠮⠳⢉⠄⠑⢔⢄⠄⠄⠄⠄⢀⢌⠂⣈⠋⠓⢁⣁⣤⣶⣗⣷⢿
⣤⣄⣀⣀⣀⣀⣤⣴⢽⣏⠄⠘⢜⡘⠜⡌⢇⠕⠄⢠⡯⣟⣽⣻⣽⣟⣾⣽⡾⣿
⣿⢽⣯⢿⣻⣽⢷⣻⣽⣞⣦⣄⣀⣀⠁⡈⣀⡠⡴⡯⡯⣗⣯⡿⣾⣽⢾⣷⣻⣟
⡯⣿⢾⣟⣯⣿⣻⣯⡷⣟⣞⢾⣝⡾⡽⣮⡳⡯⣫⢯⢯⣻⣞⣿⣳⣟⡿⣞⣷⣻
⢝⣞⣯⣟⣷⢯⣷⢿⣽⣟⣾⣳⣗⡯⣟⡾⡽⣝⣗⡯⣗⢷⣻⣽⢷⣻⣟⣽⢞⢮
  _____________________________________
  |                                   |
  |        Lachonete Alegria          |
  |___________________________________|
  | Produto         | Código | Preço  |
  | Cachorro Quente |  100   | R$1,20 |
  | Bauru Simples   |  101   | R$1,30 |
  | Bauru com ovo   |  102   | R$1,50 |
  | Hambúrguer      |  103   | R$1,20 |
  | Cheeseburguer   |  104   | R$1,30 |
  | Refrigerante    |  105   | R$1,00 |
  |_________________|________|________|
''')
print("")

while produto != 0:
  produto = int(input("Digite qual o codigo do produto ou 0 para finalizar o programa: "))
  quantidade = int(input("Digite a quantidade de produtos: "))

  if produto == 100:
    preco = quantidade * 1.20
    total += preco
    print(f"Ficou em um total de RS{preco}")

  elif produto == 101:
    preco = quantidade * 1.30
    total += preco
    print(f"Ficou em um total de RS{preco}")

  elif produto == 102:
    preco = quantidade * 1.50
    total += preco
    print(f"Ficou em um total de RS{preco}")

  elif produto == 103:
    preco = quantidade * 1.20
    total += preco
    print(f"Ficou em um total de RS{preco}")

  elif produto == 104:
    preco = quantidade * 1.30
    total += preco
    print(f"Ficou em um total de RS{preco}")

  elif produto == 105:
    preco = quantidade * 1.00
    total += preco
    print(f"Ficou em um total de RS{preco}")

print("")
print(f"Foram adicionados {quantidade} itens com o total de R${total}")
print("")
print('''
 ⣠⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⡄⣄⠀⠀⠀⠀ ⠀⠀⠀
 ⢂⠏⡴⢂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣜⠳⡍⢢⠁⠀⠀⠀ ⠀⠀⠀
 ⠈⠘⡔⣫⢞⣤⣶⣾⣶⣿⣿⣷⣶⣶⣿⣿⣶⣿⣶⣍⡣⢈⠆⠁⠀⠀⠀ ⠀⠀⠀⠀
 ⠘⣽⠿⠿⠿⣿⣯⣿⡿⣯⢿⣿⣿⣿⡯⢜⡱⢫⣿⠷⠯⣄⠀⠀⠀⠀ ⠀⠀⠀⠀
 ⢸⣽⠀⠀⡀⠀⠉⢷⣿⣿⣿⣿⣿⡿⣽⢪⣝⠋⡀⠀⠀⠸⠄⠀⠀⠀ ⠀⠀⠀
 ⢠⣾⠇⠀⠀⠀⠀⠀⣀⠻⣿⣿⣿⣿⣿⣽⣧⢇⠀⠀⠀⠀⠈⣆⠀⠀⠀ ⠀⠀⠀
 ⣿⢿⣿⣦⣤⣤⣤⣶⣿⣷⣻⣟⣿⣿⣿⣿⣾⣏⡳⢶⣤⣴⣴⡣⠆⠀⠀ ⠀⠀
 ⢀⣯⣟⣿⣿⣿⣿⣿⣿⣿⣿⣷⣯⡟⣿⢻⠟⢷⠛⠝⠫⣟⠿⣭⡓⠆⠀⠀ ⠀⠀⠀
 ⣿⣾⣟⡾⣽⢻⣿⣿⣿⣿⣿⠳⠉⠆⢉⠈⠄⠂⠈⠀⢈⣿⣲⠹⠀⠀⠀ ⠀⠀⠀
 ⣿⣷⣏⣞⡽⣿⣿⣿⣿⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⣈⡷⣭⢳⡄⠀⠀ ⠀⠀⠀
 ⣿⣿⣾⡽⣾⣿⣿⠿⡿⢛⠏⢯⡙⠲⡀⠀⠀⠀⢀⠰⡈⡑⠎⡹⠀⠀⠀ ⠀
 ⣠⣾⣿⣿⣿⣿⣿⣏⣏⠳⡑⢊⠜⠠⠈⠁⠐⠀⠀⠀⠀⠂⠐⠀⠂⠡⠁⠀⠀
 ⢠⣿⣿⣿⣿⣿⣿⣿⣿⣮⡱⣀⠂⡈⠀⠠⠀⠀⠀⠀⠀⠀⢀⠀⠀⠈⠀⠀⠀⠀
 ⣾⣿⣿⣿⣿⣿⣿⣿⣿⣳⢿⡱⢃⠤⠁⡀⠀⠀⠀⠀⢀⠈⢀⠈⠀⠀⠀⠀⠀⠀
 ⣿⣿⣿⣿⣿⣟⡻⣝⠞⣭⠲⡉⢋⠤⢁⠀⠈⠀⠄⠁⠀⠀⡀⠠⠀

 Obrigado por pedir na lanchonete mais legal do mundo!!
''')

"""## 12. Em uma eleição presidencial existem quatro candidatos. Os votos são informados por meio de código.
Os códigos utilizados são:

- 1, 2, 3, 4 - Votos para os respectivos candidatos
- (você deve montar a tabela ex: 1 - Jose/ 2- João/etc)
- 5 - Voto Nulo
- 6 - Voto em Branco

Faça um programa que calcule e mostre:

- O total de votos para cada candidato;
- O total de votos nulos;
- O total de votos em branco;
- A percentagem de votos nulos sobre o total de votos;
- A percentagem de votos em branco sobre o total de votos.

Para finalizar o conjunto de votos tem-se o valor zero.
"""

votosCand1 = 0
votosCand2 = 0
votosCand3 = 0
votosCand4 = 0
nulo = 0
branco = 0

total_votos = 0

print(" ----Urna legitima---- \n candidato1 - 1 \n candidato2 - 2 \n candidato3 - 3 \n candidato4 - 4 \n Nulo - 5 \n Branco - 6")
print("")

while True:
  voto = int(input("Digite o código do candidato ou 0 para encerrar o programa: "))

  if voto == 0:
        break
  if voto == 1:
    votosCand1 += 1

  elif voto == 2:
    votosCand2 += 1

  elif voto == 3:
    votosCand3 += 1

  elif voto == 4:
    votosCand4 += 1

  elif voto == 5:
    nulo += 1

  elif voto == 6:
    branco += 1

  total_votos += 1

percNulo = (nulo / total_votos) * 100
percBranco = (branco / total_votos) * 100

print("")
print(f" candidato 1: {votosCand1} \n candidato 2: {votosCand2} \n candidato 3: {votosCand3} \n candidato 4: {votosCand4} \n nulo: {nulo} com percentual de {percNulo:.2f}% sobre o total \n branco: {branco} com percentual de {percBranco:.2f}% sobre o total\n ")